### ISSUE TITLE
automated assignment emails

### ISSUE THREAD

**Issue by cesarhb** [mshanemc/roundRobinProcessBuilder#7]
Hi, we've recently installed your Round Robin package to production just this week and all of a sudden our users have been getting the Salesforce system generated lead assignment emails. From the outset I want to say that this could be coming from a number of places, so I just want to rule out your package as the source of these emails. 

In fact, I have not encountered these emails in the sandbox (pre-production rollout) while testing your package. Just want some quick feedback to confirm whether or not your package triggers those auto lead assignment notification emails along with routing? thanks in advance.

**Comment by mshanemc** [comment]
I'm not really sure.  If you're re-assigning leads, then the emails might be triggered.  

And based on what I just saw on ideas, there might not be a way to turn those off.  If that's the case, you're going to have this issue with anything that assigns leads using code.
https://success.salesforce.com/ideaView?id=08730000000Z44aAAC

Sandboxes typically change all the email addresses and/or have email notifications turned off so that you're not spamming users (or customers!) from test data, so you might not have seen them.

**Comment by cesarhb** [comment]
Thanks @mshanemc I'm still exploring, though I did find this on the Trailblazer community as a way to disable the lead assignment emails (still not convinced it's from your RR package): https://help.salesforce.com/articleView?id=000330196&type=1&mode=1
